// SPDX-License-Identifier: MIT OR Apache-2.0
//! Shared, cross-crate test fixtures.
#![allow(missing_docs)]

pub const TEST_DID_PLC: &str = "did:plc:2qrnyk7dr5pkqe4ogsb7omzd";
pub const TEST_DID_WEB: &str = "zanbaldwin.com";

pub const TEST_DID_ROTATION_PUBLIC: &str = "did:key:zDnaeytEKXCcL5eXR6TxoeQ4eHbQjHS18FkdkdexAtNT8xVqW";
pub const TEST_DID_ROTATION_PRIVATE: &str = "z42tyu5iiyTA8GsrvMRKEw4cmvPvnRVdNARySp27MqPVyBcH";
pub const TEST_DID_SIGNING_PUBLIC: &str = "did:key:zDnaecFc6jtpxPL8NJFiVdzhz1X3UvPY2AquuA1ZU1hCotPKZ";
pub const TEST_DID_SIGNING_PRIVATE: &str = "z42tjePETmgNK7aE9zfQJ5HfN2xSbUVQsEjgRmXkQtqXoBXV";

pub const TEST_DID_KEY_USER_ALT_ROTATION1: &str = "did:key:zDnaekjEkoZtigVZukdmRaRC4QFuhaA8JKiBqDcNXGa9fNBgo";
pub const TEST_DID_KEY_USER_ALT_ROTATION2: &str = "did:key:zDnaebKw37TUUw9C2oMjjnJofoqntbCQP58EAQ9v5pbYSGJ29";
pub const TEST_DID_KEY_USER_ALT_SIGNING: &str = "did:key:zDnaegCtDGB4jF4BjCQQbssCokiDMhZapQxCG7VkJZ3zeRA1e";
pub const TEST_DID_KEY_OPERATOR: &str = "did:key:zDnaerFcnAaXwpKeaV7hCMakASetynxCgYiS1gxLUqpSzM91R";
pub const TEST_DID_KEY_ATTACKER: &str = "did:key:zDnaefVHwaR4UqLek2hWdyvZXwiM3STxJotD8GixxtuVajJQB";

// It's me!
pub const TEST_AUDIT_CHAIN: &str = r#"[
    {"did":"did:plc:2qrnyk7dr5pkqe4ogsb7omzd","operation":{"sig":"2ppmbUjV_duwAOaAhBDgoUv3WHDubty5TFFDKcuKK8oST_0SsVRTrfVz39LNwbItZEc_FkKvr0kh6MihE2xyiQ","prev":null,"type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://shimeji.us-east.host.bsky.network"}},"alsoKnownAs":["at://zanbaldwin.bsky.social"],"rotationKeys":["did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shqY2WLBcCaa58xHX4TNpayAj9C7Y8TXyQg4fM5HQ5WMzG"}},"cid":"bafyreiguelocxy4pl2ubhdruqp3tgi3lf27k6l7zm5vbvzpq7zxubbp5vu","nullified":false,"createdAt":"2023-12-04T12:44:38.479Z"},
    {"did":"did:plc:2qrnyk7dr5pkqe4ogsb7omzd","operation":{"sig":"XzDW3M3bszIHsHimnqjpXO5uWyFlHyCec4Up6o9EedcIGF_hlwWxnby8fIm4axzj5BR6Bw5aiM9JIH7hJ3UfEQ","prev":"bafyreiguelocxy4pl2ubhdruqp3tgi3lf27k6l7zm5vbvzpq7zxubbp5vu","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://shimeji.us-east.host.bsky.network"}},"alsoKnownAs":["at://zanbaldwin.com"],"rotationKeys":["did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shqY2WLBcCaa58xHX4TNpayAj9C7Y8TXyQg4fM5HQ5WMzG"}},"cid":"bafyreicjmfw2mjonx7zz77nsngs3obkuj3staqtlmsis77xeswgvcr5y2i","nullified":false,"createdAt":"2024-02-06T18:28:13.204Z"},
    {"did":"did:plc:2qrnyk7dr5pkqe4ogsb7omzd","operation":{"sig":"ABgsDe2BO55abzzoQWjJjW287JiC3mI48-azW7bY0OkzWfRfdUd7WOe_cESLiTAUS5dxV-x8WhrdSnpqRQQstQ","prev":"bafyreicjmfw2mjonx7zz77nsngs3obkuj3staqtlmsis77xeswgvcr5y2i","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://shimeji.us-east.host.bsky.network"}},"alsoKnownAs":["at://zanbaldwin.com"],"rotationKeys":["did:key:zDnaeYhzavkAFRGtQKJ7RC4Rb627RyhNWtthbmrmTXc2SsY6V","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shqY2WLBcCaa58xHX4TNpayAj9C7Y8TXyQg4fM5HQ5WMzG"}},"cid":"bafyreieu22h63hwr6m5r5tjoxwsvj2qbppurd4j4pzjrsfaot224jshpum","nullified":false,"createdAt":"2026-06-18T10:49:52.009Z"}
]"#;
pub const TEST_AUDIT_DATA: &str = r#"{
    "did":"did:plc:2qrnyk7dr5pkqe4ogsb7omzd",
    "verificationMethods":{"atproto":"did:key:zQ3shqY2WLBcCaa58xHX4TNpayAj9C7Y8TXyQg4fM5HQ5WMzG"},
    "rotationKeys":["did:key:zDnaeYhzavkAFRGtQKJ7RC4Rb627RyhNWtthbmrmTXc2SsY6V","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],
    "alsoKnownAs":["at://zanbaldwin.com"],
    "services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://shimeji.us-east.host.bsky.network"}}
}"#;

// Literally the only organic forked audit chain I could find. Even if it is benign.
pub const TEST_FORK_CHAIN: &str = r#"[
    {"did":"did:plc:ljunxbzebevrkafxaiawfgof","operation":{"sig":"YzHPeA1EIIRBYW9JID6-m95ruswXqgYT7TOhTz5mqq1P8UWm83kzTD0ZniDuIkIV_iDEl-iqMI1w6eQfB83AJg","prev":null,"type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://hygrophorus.us-west.host.bsky.network"}},"alsoKnownAs":["at://al-aighumaisa.bsky.social"],"rotationKeys":["did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shZ7QmDQvNqxj9uLsxsRH6yw3q9SmPyyVxn6J5MWBTS3wZ"}},"cid":"bafyreic2ndnyojajfmkqbnycafrjtriswrteycfh4dofnweudmpcqlnjii","nullified":false,"createdAt":"2025-12-31T13:09:40.310Z"},
    {"did":"did:plc:ljunxbzebevrkafxaiawfgof","operation":{"sig":"Z9KD8rmun4MDLmvA63rFpW3X3wSRVvD70J20C2rDCgw8AFak5jZJ8RYHVn37j7jnyBQZIWmE3Mkc8LI0-UjW4g","prev":"bafyreic2ndnyojajfmkqbnycafrjtriswrteycfh4dofnweudmpcqlnjii","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://hygrophorus.us-west.host.bsky.network"}},"alsoKnownAs":["at://al-aighumaisa.okazu-diary.org"],"rotationKeys":["did:key:zQ3shwFzVM6neH7QTewwUVhB2Z1UySpFHse7JKyC8KQSjhpYZ","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shZ7QmDQvNqxj9uLsxsRH6yw3q9SmPyyVxn6J5MWBTS3wZ"}},"cid":"bafyreia6y7trwtxzhq2jdu6rf25lzvygjq4wrr3viufkkb4zdosrpj3o6i","nullified":false,"createdAt":"2025-12-31T21:43:46.403Z"},
    {"did":"did:plc:ljunxbzebevrkafxaiawfgof","operation":{"sig":"bFf7Tj0bLvWk3s3fsz1zRELD8AmZPMOSA4PyHvOZKg9jzRZUR5x7rOq08lyM9VZiRZQLIZOVtJCYf3kBWqhFDg","prev":"bafyreia6y7trwtxzhq2jdu6rf25lzvygjq4wrr3viufkkb4zdosrpj3o6i","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://hygrophorus.us-west.host.bsky.network"}},"alsoKnownAs":["at://al-aighumaisa.okazu-diary.org"],"rotationKeys":["did:key:zQ3shwFzVM6neH7QTewwUVhB2Z1UySpFHse7JKyC8KQSjhpYZ","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shZ7QmDQvNqxj9uLsxsRH6yw3q9SmPyyVxn6J5MWBTS3wZ"}},"cid":"bafyreidxyjtblpax5b5sijjk4pn2pmd35rnitlqoqarml4ebg2whw6obsu","nullified":true,"createdAt":"2026-01-01T11:40:25.400Z"},
    {"did":"did:plc:ljunxbzebevrkafxaiawfgof","operation":{"sig":"PMgNwo01hxWOnVKp2WUEVJm7Dt-Qvgu2vwhpoLJbKTAGc00KNP4mws_lG6Oa6UVbvZ4BLntld1V8FHlLi-sCLA","prev":"bafyreia6y7trwtxzhq2jdu6rf25lzvygjq4wrr3viufkkb4zdosrpj3o6i","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://hygrophorus.us-west.host.bsky.network"}},"alsoKnownAs":["at://al-aighumaisa.okazu-diary.org"],"rotationKeys":["did:key:zQ3shwFzVM6neH7QTewwUVhB2Z1UySpFHse7JKyC8KQSjhpYZ","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shZ7QmDQvNqxj9uLsxsRH6yw3q9SmPyyVxn6J5MWBTS3wZ"}},"cid":"bafyreigrgbcj7yqhnnc2hpxj42a2zbgai7ibrzqgu5evb52gz6fy6yraou","nullified":false,"createdAt":"2026-01-01T12:13:57.522Z"}
]"#;
pub const TEST_FORK_DATA: &str = r#"{
    "did":"did:plc:ljunxbzebevrkafxaiawfgof",
    "verificationMethods":{"atproto":"did:key:zQ3shZ7QmDQvNqxj9uLsxsRH6yw3q9SmPyyVxn6J5MWBTS3wZ"},
    "rotationKeys":["did:key:zQ3shwFzVM6neH7QTewwUVhB2Z1UySpFHse7JKyC8KQSjhpYZ","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],
    "alsoKnownAs":["at://al-aighumaisa.okazu-diary.org"],
    "services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://hygrophorus.us-west.host.bsky.network"}}
}"#;

// Paul Frazee, the first did:plc ever.
pub const TEST_LEGACY_CHAIN: &str = r#"[
    {"did":"did:plc:ragtjsm2j2vknwkz3zp4oxrd","operation":{"sig":"DyaPWDItkJnVkN1izINSW-fdjUzP9BkIKlD7SnzD5axfK_870ZZ-1EYcrQLQtP9VkWcp2cdbyIHprjPfeUs8WQ","prev":null,"type":"create","handle":"paul.bsky.social","service":"https://bsky.social","signingKey":"did:key:zQ3shP5TBe1sQfSttXty15FAEHV1DZgcxRZNxvEWnPfLFwLxJ","recoveryKey":"did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg"},"cid":"bafyreieibu2mtgsovktnswo6l7dv4i4ztioutzpsy7wsasmbznzqxkpyje","nullified":false,"createdAt":"2022-11-17T00:35:16.391Z"},
    {"did":"did:plc:ragtjsm2j2vknwkz3zp4oxrd","operation":{"sig":"m__rIh2e-b-vpQACuAaFKRVrW2LxidRiBJZn6v62MLBt3p7XbUl5qU8hAfIxtb7VYo_XUwwbvOumL4FN9tKo3g","prev":"bafyreieibu2mtgsovktnswo6l7dv4i4ztioutzpsy7wsasmbznzqxkpyje","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://bsky.social"}},"alsoKnownAs":["at://pfrazee.com"],"rotationKeys":["did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shP5TBe1sQfSttXty15FAEHV1DZgcxRZNxvEWnPfLFwLxJ"],"verificationMethods":{"atproto":"did:key:zQ3shP5TBe1sQfSttXty15FAEHV1DZgcxRZNxvEWnPfLFwLxJ"}},"cid":"bafyreiawashg6n7iopvfmdqnfkkovqgboafproke5wkr6zvoqn3wkq7nbq","nullified":false,"createdAt":"2023-03-07T21:31:46.627Z"},
    {"did":"did:plc:ragtjsm2j2vknwkz3zp4oxrd","operation":{"sig":"cdswkyd7UCh5-syFDTNfvYizb3A5F1rr3hW7zR46ukYJrBAEa1sfcp7brxID6fXZu5iZ1de8RwbaHu1xkg0HYg","prev":"bafyreiawashg6n7iopvfmdqnfkkovqgboafproke5wkr6zvoqn3wkq7nbq","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://bsky.social"}},"alsoKnownAs":["at://pfrazee.com"],"rotationKeys":["did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF"}},"cid":"bafyreignfrawbnz7ua7ga7e3dmfg2xfdug2bc6jjdudqmbfkahriyazire","nullified":false,"createdAt":"2023-03-09T23:18:30.891Z"},
    {"did":"did:plc:ragtjsm2j2vknwkz3zp4oxrd","operation":{"sig":"0Yzs2tCtY9sw-K7HR2OZJu-KgjsjVO5vEOJ0Y5Ge2JE8siUBHu9oPcEw8w36jtr6IbRHz_WORh0NxD-2K9qP9A","prev":"bafyreignfrawbnz7ua7ga7e3dmfg2xfdug2bc6jjdudqmbfkahriyazire","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://morel.us-east.host.bsky.network"}},"alsoKnownAs":["at://pfrazee.com"],"rotationKeys":["did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shbTzUCq5zuk7oSj5zaJndqWhjwGDaGuvBXpjg8C19qssW"}},"cid":"bafyreihs6hh3yfgbaz55dkpoguyaz4ipws67223abp24kuykk4rc2wjonu","nullified":false,"createdAt":"2023-11-07T01:40:28.431Z"},
    {"did":"did:plc:ragtjsm2j2vknwkz3zp4oxrd","operation":{"sig":"CxF2C53WrrtkRWQAz_qa3jPnflFf4kK08iDbG62xuJM6Uc6dogZXfAw6KtOFV8zKANn3CqZZ_1DtxraSHaxoKQ","prev":"bafyreihs6hh3yfgbaz55dkpoguyaz4ipws67223abp24kuykk4rc2wjonu","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://morel.us-east.host.bsky.network"}},"alsoKnownAs":["at://crandelheimer.bsky.social"],"rotationKeys":["did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shbTzUCq5zuk7oSj5zaJndqWhjwGDaGuvBXpjg8C19qssW"}},"cid":"bafyreiatwvtyaofoto7znhheom3hd7bk25b22dn4bbwcu3ez6gejvvy4by","nullified":false,"createdAt":"2023-11-07T19:50:57.995Z"},
    {"did":"did:plc:ragtjsm2j2vknwkz3zp4oxrd","operation":{"sig":"jjJO_xAtRkhTUl97DsNTC0LvY1O7n0g8WM5OPe8KYRguHMCFUmUriYEiBojRviqsAjQ2YjyH3AwIudYksxSIsw","prev":"bafyreiatwvtyaofoto7znhheom3hd7bk25b22dn4bbwcu3ez6gejvvy4by","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://morel.us-east.host.bsky.network"}},"alsoKnownAs":["at://pfrazee.com"],"rotationKeys":["did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shbTzUCq5zuk7oSj5zaJndqWhjwGDaGuvBXpjg8C19qssW"}},"cid":"bafyreic54ippollqvcarmc3pddd6gwzwllekpsln6ixakosz3x2z2gl5h4","nullified":false,"createdAt":"2023-11-07T19:53:14.626Z"}
]"#;
pub const TEST_LEGACY_DATA: &str = r#"{
    "did":"did:plc:ragtjsm2j2vknwkz3zp4oxrd",
    "verificationMethods":{"atproto":"did:key:zQ3shbTzUCq5zuk7oSj5zaJndqWhjwGDaGuvBXpjg8C19qssW"},
    "rotationKeys":["did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],
    "alsoKnownAs":["at://pfrazee.com"],
    "services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://morel.us-east.host.bsky.network"}}
}"#;

// Official `did-method-plc` interop vectors.
pub const TEST_INTEROP_CHAIN: &str = r#"[
    {"did":"did:plc:ana7n2ppeqk57pay7azhjs24","operation":{"sig":"IypAT0szH_8Ygl7QrnXZrxemIcg_RkW_GyYbjih_9BEe5DRGgLxmQGeWsvB0TfDqm50c0xB8mGraOf25IA25qA","prev":null,"type":"plc_operation","services":{},"alsoKnownAs":["at://op0"],"rotationKeys":["did:key:zQ3shhiASLv8GN7ob3iWqsAxP7nE95LUPWsNEb2jTfW7e2yCt","did:key:zQ3shsnWCW7HC7bYVnRcY5XxQpKArfafpB5S39DoqTkexuiTu"],"verificationMethods":{}},"cid":"bafyreiadih3ot3zecxp3yghygj2mwxh3szrrifwer2z4iodazbrtuvmmgm","nullified":false,"createdAt":"2025-12-09T18:59:01.605Z"},
    {"did":"did:plc:ana7n2ppeqk57pay7azhjs24","operation":{"sig":"eabKT5-1i2MW8Z7iWXHp2tlEYn1y6HmbuHexP-fgOzQq6RuNBGlWWOjMygxl8BK98FCNU8wvX9eWkM-soBrfow","prev":"bafyreiadih3ot3zecxp3yghygj2mwxh3szrrifwer2z4iodazbrtuvmmgm","type":"plc_operation","services":{},"alsoKnownAs":["at://op1"],"rotationKeys":["did:key:zQ3shXPgp1NrzoXSpa7YTn9ZFUVco39X8ygph16Bj6Ku4NJd2","did:key:zQ3shd4eC3ykuq1GfpuyosoBLSX3JASu9qFXggqWGWwH9MXg6"],"verificationMethods":{}},"cid":"bafyreieshd5ujokbnxfzqmaoyimbdsiuwklji2st7ffga2vkhsozxn324u","nullified":false,"createdAt":"2025-12-09T18:59:10.248Z"},
    {"did":"did:plc:ana7n2ppeqk57pay7azhjs24","operation":{"sig":"hHkc9Mn_nE-P60GsZJG6jm6xdlBUbaxonGsir-O95P1ibH16jK-FyVO2KtF-J2llULLDZID_mbKkh2QOpBc-TA","prev":"bafyreieshd5ujokbnxfzqmaoyimbdsiuwklji2st7ffga2vkhsozxn324u","type":"plc_operation","services":{},"alsoKnownAs":["at://op2"],"rotationKeys":["did:key:zQ3shco8HcC3YKPeoCJ55S9XQ7e7enn6qqCeyx1jhxGE8hRAX","did:key:zQ3shQDMSvL951qcX2Tpdp4s6tL39pjMzVowM9XU4v6NMkG92"],"verificationMethods":{}},"cid":"bafyreifpq7r5ipo3rdpfrippmir5ne6he36mfab2shtz5g25tjm6z655rq","nullified":true,"createdAt":"2025-12-09T18:59:16.224Z"},
    {"did":"did:plc:ana7n2ppeqk57pay7azhjs24","operation":{"sig":"MoCicrrAaerQdkyGeZT5QFKQ5hUbwoELlpJG1yq8e1onpuIECPlDkRn0MSTSPK8t546W8jZNvrtHRuNCBoXQUA","prev":"bafyreifpq7r5ipo3rdpfrippmir5ne6he36mfab2shtz5g25tjm6z655rq","type":"plc_operation","services":{},"alsoKnownAs":["at://op3"],"rotationKeys":["did:key:zQ3shX4Tw63vH57eanTngtGeGXDTjDYqovNd8DfpNpcJsHRwK","did:key:zQ3shTPSgYbFTfmV5wNDV6oHHogTsDemWRdwWm6ZKZB2wXDQc"],"verificationMethods":{}},"cid":"bafyreih55jjrlxemxyusbyqhwkydvew5seldzlzflhuiqhsuwienbuvxmu","nullified":true,"createdAt":"2025-12-09T18:59:22.048Z"},
    {"did":"did:plc:ana7n2ppeqk57pay7azhjs24","operation":{"sig":"lD4kyQq8GZbvqaUHLt91wCBZgxeFvXQdVLM7Go0083cLE8HeG1Rj5HnsEBadYqzoCOcLgDWPMCwdAuM_GCojxA","prev":"bafyreih55jjrlxemxyusbyqhwkydvew5seldzlzflhuiqhsuwienbuvxmu","type":"plc_operation","services":{},"alsoKnownAs":["at://op4"],"rotationKeys":["did:key:zQ3shW9AesYJE95cyuPwWCmJhvPgP7Rkva8SgNoJ2wuAA7gDd","did:key:zQ3shaw1oqEGsigCdjMvgUD6sN4w6r3h3EdG7Eqp54c7oo6LD"],"verificationMethods":{}},"cid":"bafyreicnmhhlbyh5qhslaub3l4j7hydcv3lbmxyorkge5y7xgpvdlxzjlu","nullified":true,"createdAt":"2025-12-09T18:59:28.015Z"},
    {"did":"did:plc:ana7n2ppeqk57pay7azhjs24","operation":{"sig":"LjSlpZATuTm28kcSAkJJmgP6_pDoq2YA5J408aQJTmVyTsDkwyJ3gKB-pcMiYKlNptD3BxdiXnIKaSP5vI6D8w","prev":"bafyreih55jjrlxemxyusbyqhwkydvew5seldzlzflhuiqhsuwienbuvxmu","type":"plc_operation","services":{},"alsoKnownAs":["at://op5"],"rotationKeys":["did:key:zQ3shvv4uX5wmumTa3U5pgZxt1VNZmHY3UhX3KhEwHk7dk7PB","did:key:zQ3shvKqwoT1wtjHbCki566vQFk86UvJc8T5WfGpmCm5jyCN7"],"verificationMethods":{}},"cid":"bafyreihveyvdjaslphmjftrb6uw2ftqklefi6jod2m7lv7pw2aitu6lrqu","nullified":true,"createdAt":"2025-12-09T18:59:33.955Z"},
    {"did":"did:plc:ana7n2ppeqk57pay7azhjs24","operation":{"sig":"tjVslQYlmnJrZifS9TqxhH7e4YolwvI40FU_X93mFVRy85W64ClwJ_1X-eeQiNh5on0TxdqoBmPcvERocrEEPA","prev":"bafyreihveyvdjaslphmjftrb6uw2ftqklefi6jod2m7lv7pw2aitu6lrqu","type":"plc_operation","services":{},"alsoKnownAs":["at://op6"],"rotationKeys":["did:key:zQ3shjaNAXa4S2zupVtaRfiiiZL8BNsz3Gx2X7u4KJP4xxVfR","did:key:zQ3shRiasZG5nANgQH2MYA2RJcZo4K6J7zL7EeoG2q46HjUyi"],"verificationMethods":{}},"cid":"bafyreihdethy553d6czdke36vlfmn7tzhjumndlkwmfksqubutzeaihcuy","nullified":true,"createdAt":"2025-12-09T18:59:40.574Z"},
    {"did":"did:plc:ana7n2ppeqk57pay7azhjs24","operation":{"sig":"AFq-UKqZtLA88ZssGg0jV7BUm1zju4V79W4KG35VdXMB7MH9AfHvBNLOlxmzEW_ATs1tmeX60U00meDI8oppRg","prev":"bafyreieshd5ujokbnxfzqmaoyimbdsiuwklji2st7ffga2vkhsozxn324u","type":"plc_operation","services":{},"alsoKnownAs":["at://op7"],"rotationKeys":["did:key:zQ3shi3dE5REVqBR25JcENfLA5qvKPy6yADo9EQCtNVGwo9Xn","did:key:zQ3shfePFkQKQMPDpfKpH5frZuk6aLsqWhLaQZQ62KsQwQziz"],"verificationMethods":{}},"cid":"bafyreihdmait2kmgp3zm7uixh4b56ekufakqwqlfgh7ji6m2aphensd3dy","nullified":false,"createdAt":"2025-12-09T18:59:46.081Z"}
]"#;
pub const TEST_INTEROP_DATA: &str = r#"{
    "did":"did:plc:ana7n2ppeqk57pay7azhjs24",
    "verificationMethods":{},
    "rotationKeys":["did:key:zQ3shi3dE5REVqBR25JcENfLA5qvKPy6yADo9EQCtNVGwo9Xn","did:key:zQ3shfePFkQKQMPDpfKpH5frZuk6aLsqWhLaQZQ62KsQwQziz"],
    "alsoKnownAs":["at://op7"],
    "services":{}
}"#;

// Organic tombstone account.
// See `did:plc:sd4ztm7wfoqmsg2u6dcizhnt` for a nullified tombstone operation.
pub const TEST_TOMBSTONE_CHAIN: &str = r#"[
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"4DnqvrVFOZS4d_qoXSv_X87G0slZHbOxflyySVLEQLEZ4N1XtFYguoPd4gsVwDW52hNNrmQVa_mVUZGRc_s9PA","prev":null,"type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://bsky.social"}},"alsoKnownAs":["at://goeo.bsky.social"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF"}},"cid":"bafyreid2tbopmtuguvuvij5kjcqo7rv7yvqza37uvfcvk5zdxyo57xlfdi","nullified":false,"createdAt":"2023-10-10T18:37:35.152Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"K0ZmWKmH0a1hMuVrvO9L-Tl5qBZBkl4IcgP5QgqLRS1FJ2tbstKRA7KIlqbmSRBi08Gb7zDkAymnAECJ2nuEFA","prev":"bafyreid2tbopmtuguvuvij5kjcqo7rv7yvqza37uvfcvk5zdxyo57xlfdi","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://bsky.social"}},"alsoKnownAs":["at://genco.me"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF"}},"cid":"bafyreiahul3cohr3je7wyfezlkzzlv66g37nq5nojcrmv6kxn6xgesh6bi","nullified":true,"createdAt":"2023-10-10T18:46:41.368Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"CyZxnGuw5eY_tQ6Zzc1vmLZDmfVnn3MkqMiPAGa1cdgdvZJkgTctPpCU9Alg1ICSYDaskcFdgPmctodC1SZ_Nw","prev":"bafyreiahul3cohr3je7wyfezlkzzlv66g37nq5nojcrmv6kxn6xgesh6bi","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://bsky.social"}},"alsoKnownAs":["at://genco.me"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY"],"verificationMethods":{"atproto":"did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF"}},"cid":"bafyreifgeojzcravnjlw3qw3nizra57iaoszgzqvit4gtjoijrab5aif3i","nullified":true,"createdAt":"2023-10-10T19:40:19.420Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"tjKH4HiMCdm9gMEDwDpwWD-NIK2aGHg8IXbiZMoPHhVhOXz8JAmNFZxEHSTJ66itdS1HYpFTUiYMO7XzxXzFCg","prev":"bafyreifgeojzcravnjlw3qw3nizra57iaoszgzqvit4gtjoijrab5aif3i","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://bsky.social"}},"alsoKnownAs":["at://cyber.crime.rocks","at://crime.rocks","at://genco.me"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY"],"verificationMethods":{"atproto":"did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF"}},"cid":"bafyreicp5wh4hc3m5qbgfxg5haau45dxdgxtz7mhi65gl5cundmuggi3fy","nullified":true,"createdAt":"2023-10-10T20:26:25.467Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"2bBoiNZh9yPAmQq9w9SNaCNu77Lf0EAwsIEKXPkLc9tVAsTHBpngQFrxBgxixDQdrpwEnjSI_fyQrxVMDiFtfw","prev":"bafyreicp5wh4hc3m5qbgfxg5haau45dxdgxtz7mhi65gl5cundmuggi3fy","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://bsky.social"}},"alsoKnownAs":["at://cyber.crime.rocks"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY"],"verificationMethods":{"atproto":"did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF"}},"cid":"bafyreihsp7jfyteidzz2im4nxncmdyxdiqucakx45or2i63vhhslxddhrm","nullified":true,"createdAt":"2023-10-10T20:34:23.366Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"wdTABQB7wYnOxQ4UwigC-JAlm0kCtPHpXdMWGX3ff10ptsDCIZcImEfBnvEET4Iiw9Nc41IKQXTArzAlXEhkPw","prev":"bafyreid2tbopmtuguvuvij5kjcqo7rv7yvqza37uvfcvk5zdxyo57xlfdi","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://bsky.social"}},"alsoKnownAs":["at://genco.me","at://crime.rocks","at://cyber.crime.rocks"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF"}},"cid":"bafyreiafe2tt3xhvufat3peri6qjqkjrv55fuxbnwtrjbfce5zdnbsdisy","nullified":false,"createdAt":"2023-10-10T20:39:50.484Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"O3a3AeWIZu-nxR_MWhFmrO2FbQ2aemtrAAHG0PwhUj1uAQGvQjdSzUz9SwczVNqgcGd45eIx-22QUfEnG-YM0g","prev":"bafyreiafe2tt3xhvufat3peri6qjqkjrv55fuxbnwtrjbfce5zdnbsdisy","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://bsky.social"}},"alsoKnownAs":["at://genco.me","at://crime.rocks","at://cyber.crime.rocks","at://drugu.se","at://recreational.drugu.se"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF"}},"cid":"bafyreifq7bmpm3kqenrxeibkzhcbxefnsu4zilphnmijb6tk2epsvxizre","nullified":false,"createdAt":"2023-10-10T20:56:34.318Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"2KGcOfxB069VkpB1kIRkBWsOScClMmJXcYvADvanosRxczx9HPeM3v4fb2kCAD6ShVwQhDta_JjRTt0DdJB11g","prev":"bafyreifq7bmpm3kqenrxeibkzhcbxefnsu4zilphnmijb6tk2epsvxizre","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://bsky.social"}},"alsoKnownAs":["at://genco.me","at://crime.rocks","at://cyber.crime.rocks","at://drugu.se","at://recreational.drugu.se","at://very.international"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF"}},"cid":"bafyreicfmqgjbbu2he4fdq4lzcr75ugylje2dleirxyfexbbfbqbqxbrhe","nullified":false,"createdAt":"2023-10-11T08:46:35.540Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"GLmekzwd_tyjRaKx-_le0VyxtLLi3dGLmevl-neg7UhTS1TAHSXdipyP9Q2y-ryrWKmy4iwThxO-uCvzBIozCA","prev":"bafyreicfmqgjbbu2he4fdq4lzcr75ugylje2dleirxyfexbbfbqbqxbrhe","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://amanita.us-east.host.bsky.network"}},"alsoKnownAs":["at://genco.me","at://crime.rocks","at://cyber.crime.rocks","at://drugu.se","at://recreational.drugu.se","at://very.international"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shoNWrZN1RSMKagL3KnJDRjYEHHZ1i6ZccBgd3UrfpNrDt"}},"cid":"bafyreidubsc3chwv7g5llgaplaozxkp42sa2qtun6ezs27qvkkhhv5hbu4","nullified":false,"createdAt":"2023-11-13T02:16:47.444Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"VIOOp2JllcDjy5h2E6Z5wrK_Wg9FssAKPv6sLvNklQRt9IkdeFL6L7qqU-XTx1Sx59b80lfvFA0qciDj7Tovlg","prev":"bafyreidubsc3chwv7g5llgaplaozxkp42sa2qtun6ezs27qvkkhhv5hbu4","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://amanita.us-east.host.bsky.network"}},"alsoKnownAs":["at://goeoeo.bsky.social","at://crime.rocks","at://cyber.crime.rocks","at://drugu.se","at://recreational.drugu.se","at://very.international"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shoNWrZN1RSMKagL3KnJDRjYEHHZ1i6ZccBgd3UrfpNrDt"}},"cid":"bafyreia57xtiqjyp6pkhvm3ygu2qfvh7drvodlmbnbn7ximqifkzrsyuzu","nullified":false,"createdAt":"2024-01-23T15:42:07.787Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"ElTbA7E7UJWgGZrpikHsvOsxDpmZgvHPXi5ZdUeQKq8h03uh9gPIVYczFAY7fY32SjS2Ll2viL6ZGM_pcGYQjw","prev":"bafyreia57xtiqjyp6pkhvm3ygu2qfvh7drvodlmbnbn7ximqifkzrsyuzu","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://amanita.us-east.host.bsky.network"}},"alsoKnownAs":["at://goeoeo.bsky.social"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF"}},"cid":"bafyreibncy6ybrhrdvtf6khzl4huqcwoup3u7aay6duxfeulmpfjtrpjd4","nullified":false,"createdAt":"2024-01-23T15:44:09.488Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"02ZKz7OG3Un9dEdVuunnGhoKuNDytNhMVLmm2pUusAxJXsEDdTn3Ho72aSwDbzzlFfZ04Ok_DsOiWLj6ajIblA","prev":"bafyreibncy6ybrhrdvtf6khzl4huqcwoup3u7aay6duxfeulmpfjtrpjd4","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://amanita.us-east.host.bsky.network"}},"alsoKnownAs":["at://goeo.bsky.social"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF"}},"cid":"bafyreidla66ol2bfnfce5bct4pszeeldqdw5basx7vdf5zfoakbvtupcie","nullified":false,"createdAt":"2024-01-23T15:45:58.027Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"pXfg5UUZDe6TvZG-nuM0U7Lhh1UuJR-xP3nh8CglxERO8B5-MzZiZwi6oSWu965S9um-uP2jiweRP9-_oaD-CA","prev":"bafyreidla66ol2bfnfce5bct4pszeeldqdw5basx7vdf5zfoakbvtupcie","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://amanita.us-east.host.bsky.network"}},"alsoKnownAs":["at://goeoeo.bsky.social"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF"}},"cid":"bafyreif5vqevgtqq75nigsxpgf22ab22wwscb5pcdfxlrd6dqxchmy4icu","nullified":false,"createdAt":"2024-01-24T12:33:09.478Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"067eMCFEjZXDErmbiGtmgn-dPXIOzndQQvOI0YG81ZsquMnat34PXrUC8om020JFZD7D5GC2tjWuuZZikRs5iQ","prev":"bafyreif5vqevgtqq75nigsxpgf22ab22wwscb5pcdfxlrd6dqxchmy4icu","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://amanita.us-east.host.bsky.network"}},"alsoKnownAs":["at://goeo.bsky.social"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF"}},"cid":"bafyreib3qkyyk7pjev5jmfgqs72ijud52uiposfnwf246mgbejqujnmuvu","nullified":false,"createdAt":"2024-01-24T12:34:16.441Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"NnrpcJuv1cWVsJaKFqCuTuxIrVJEl5XxenAZKEKJvZpkjhi3IpasN19_Ev41fjQcfl1H7VICGVUVJwfbr5fyEQ","prev":"bafyreib3qkyyk7pjev5jmfgqs72ijud52uiposfnwf246mgbejqujnmuvu","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://amanita.us-east.host.bsky.network"}},"alsoKnownAs":["at://goeoeo.bsky.social"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shoNWrZN1RSMKagL3KnJDRjYEHHZ1i6ZccBgd3UrfpNrDt"}},"cid":"bafyreid5fsoaqf6utrqr7f3oyqd7kym6dnb2ha264in3mhf6bsp4xqsrim","nullified":false,"createdAt":"2024-01-24T12:34:47.171Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"QceN7rRgWREpRPcChJNomt5SVTFxkck2_ZzCAl1FisRdgoWBdELLN5217Uy0m0XGG8PQ410KozNORL0IlxT8LA","prev":"bafyreid5fsoaqf6utrqr7f3oyqd7kym6dnb2ha264in3mhf6bsp4xqsrim","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://amanita.us-east.host.bsky.network"}},"alsoKnownAs":["at://goeo1.bsky.social"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shoNWrZN1RSMKagL3KnJDRjYEHHZ1i6ZccBgd3UrfpNrDt"}},"cid":"bafyreifzsayjsfxjwjhhljavy5tsbkm7por34lkkldppm5heyji4ii3k6u","nullified":false,"createdAt":"2024-01-30T20:41:54.367Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"sQugizkvp6wbngY3rpMkdOwwX-egkkROPfGQjmNL62x83Geit2OVXSBQ0tnArpu74ai48jWzZ88MN4QmJaHuSQ","prev":"bafyreifzsayjsfxjwjhhljavy5tsbkm7por34lkkldppm5heyji4ii3k6u","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://amanita.us-east.host.bsky.network"}},"alsoKnownAs":["at://goeo.bsky.social"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY","did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg","did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"],"verificationMethods":{"atproto":"did:key:zQ3shoNWrZN1RSMKagL3KnJDRjYEHHZ1i6ZccBgd3UrfpNrDt"}},"cid":"bafyreia6oqjm7fci5luqskzgi6zd3dckxs6gncf4moraiinslnogtqck64","nullified":false,"createdAt":"2024-01-30T20:42:03.755Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"3bocPwTp9Z1KXnesWKZni0lLzIz4vFYD89yTtLotvT9WbcfPGaKzAd2McmACmqFM0vZO2XV3wQ8ngK8an5RixQ","prev":"bafyreia6oqjm7fci5luqskzgi6zd3dckxs6gncf4moraiinslnogtqck64","type":"plc_operation","services":{"atproto_pds":{"type":"AtprotoPersonalDataServer","endpoint":"https://goeo.lol"}},"alsoKnownAs":["at://goeoeo.bsky.social"],"rotationKeys":["did:key:zDnaepbLeZpNrs4jp24Rio9CumZzws9avgn8MDxgt63d8hPeY"],"verificationMethods":{"atproto":"did:key:zQ3shoNWrZN1RSMKagL3KnJDRjYEHHZ1i6ZccBgd3UrfpNrDt"}},"cid":"bafyreidifsxv2nqst2so6tdajaaiur3dsfm2olwoxcbnrbawvtwi3v7wky","nullified":false,"createdAt":"2024-03-05T04:49:17.116Z"},
    {"did":"did:plc:pkmfz5soq2swsvbhvjekb36g","operation":{"sig":"WZHRGMyDAjORhzgwgL_DvHoWc3wD3B4lZHcFtQc7TJhcdoLsTYXbWVc_H4LwnopdaAo5dasLGhRt3qlyZ5TeDQ","prev":"bafyreidifsxv2nqst2so6tdajaaiur3dsfm2olwoxcbnrbawvtwi3v7wky","type":"plc_tombstone"},"cid":"bafyreiffflgoag5fasdw3x3zagw7wsalqaskzpp5j4cw34ohuax6r2a6te","nullified":false,"createdAt":"2024-03-05T04:50:02.819Z"}]
"#;
pub const TEST_TOMBSTONE_DATA: &str = r#"{
    "message":"DID not available: did:plc:pkmfz5soq2swsvbhvjekb36g"
}"#;
