name: 'CI'

on:
  push:
    branches: ['main']
  pull_request:

permissions:
  contents: 'read'

env:
  CARGO_TERM_COLOR: 'always'

jobs:
  lockfile:
    name: 'Lockfile'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v7'
      - name: 'Install toolchain'
        run: 'rustup toolchain install'
      - uses: 'Swatinem/rust-cache@v2'
      - run: 'cargo metadata --locked --format-version 1 >/dev/null'

  build:
    name: 'Dev Build'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v7'
      - name: 'Install toolchain'
        run: 'rustup toolchain install'
      - uses: 'Swatinem/rust-cache@v2'
      - run: 'cargo build --workspace --all-targets --locked'

  build-deploy:
    name: 'Deploy Build (musl)'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v7'
      - name: 'Install musl-tools'
        run: 'sudo apt-get update && sudo apt-get install -y musl-tools'
      - name: 'Install toolchain'
        run: |
          rustup toolchain install
          rustup target add x86_64-unknown-linux-musl
      - uses: 'Swatinem/rust-cache@v2'
      - run: 'cargo deploy --workspace --locked'

  clippy:
    name: 'Clippy'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v7'
      - name: 'Install toolchain'
        run: 'rustup toolchain install'
      - uses: 'Swatinem/rust-cache@v2'
      - run: 'cargo clippy --workspace --all-targets --locked -- -D warnings'

  docs:
    name: 'Docs'
    runs-on: 'ubuntu-latest'
    env:
      RUSTDOCFLAGS: '-D warnings'
    steps:
      - uses: 'actions/checkout@v7'
      - name: 'Install toolchain'
        run: 'rustup toolchain install'
      - uses: 'Swatinem/rust-cache@v2'
      - run: 'cargo doc --workspace --no-deps --locked'
